version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_store_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - store_network
    # Строгая проверка: порт открыт + база отвечает на SQL-запрос
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d my_store_db && psql -U user -d my_store_db -c 'SELECT 1;'"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s  # Даем 5 секунд на инициализацию системных файлов базы

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - store_network

  backend:
    build:
      context: ./backend  # Укажи путь к папке, где лежит твой Dockerfile бэкенда
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/my_store_db
    depends_on:
      db:
        condition: service_healthy
    # Подстраховка перед стартом uvicorn, чтобы asyncpg наверняка зацепился
    command: sh -c "sleep 2 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - store_network

# Именованные вольюмы для данных
volumes:
  postgres_data:
  pgadmin_data:

# Общая докер-сеть
networks:
  store_network:
    driver: bridge